version: '3.8'

services:
  bytetrack:
    build: .
    image: bytetrack:latest
    container_name: bytetrack
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    volumes:
      - ./pretrained:/workspace/ByteTrack/pretrained
      - ./datasets:/workspace/ByteTrack/datasets
      - ./YOLOX_outputs:/workspace/ByteTrack/YOLOX_outputs
      - /tmp/.X11-unix/:/tmp/.X11-unix:rw
    devices:
      - /dev/video0:/dev/video0
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true 